Feature/mapeamento guarda
KauaAmaral/Entra21-Trabalho-Final pull request #19
Opened 2022-08-31 23:34 UTC by wscaburri

2022-08-31 23:37 UTC, leonardopokreweckysalvador requested changes

2022-08-31 23:37 UTC, leonardopokreweckysalvador commented on Repository/Repositories/Guards/GuardRepository.cs
> +        public bool Apagar(int id)
Colocar os métodos no padrão

2022-08-31 23:37 UTC, leonardopokreweckysalvador commented on Repository/Repositories/Guards/IGuardRepository.cs
> +        Guard Cadastrar(Guard guard);
Colocar os métodos no padrão

2022-09-01 00:05 UTC, wscaburri commented on Repository/Repositories/Guards/GuardRepository.cs
> +        public bool Apagar(int id)
Corrigido

2022-09-01 00:05 UTC, wscaburri commented on Repository/Repositories/Guards/IGuardRepository.cs
> +        Guard Cadastrar(Guard guard);
Corrigido

2022-09-01 00:06 UTC, merged