Feature/controle hierarquia usuario
KauaAmaral/Entra21-Trabalho-Final pull request #80
Opened 2022-09-29 23:48 UTC by mertensefraim

2022-09-29 23:55 UTC, KauaAmaral commented on Application/Areas/Administrator/Controllers/UserController.cs
> +
Remover Linha

2022-09-29 23:55 UTC, KauaAmaral commented on Application/Areas/Guard/Controllers/UserController.cs
> +
Remover Linha

2022-09-29 23:55 UTC, KauaAmaral commented on Service/Services/Users/UserService.cs
> +
Remover Linha

2022-09-29 23:58 UTC, claudio255 requested changes

2022-09-29 23:58 UTC, claudio255 commented on Application/Areas/Guard/Controllers/UserController.cs
> +
Linha em branco

2022-09-30 00:00 UTC, KauaAmaral approved these changes

2022-09-30 00:00 UTC, claudio255 approved these changes

2022-09-30 00:01 UTC, merged